---
title: "General Social Survey"
author: "David Jackson"
date: "`Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(scales)
library(janitor)
library(writexl)
```

### Import SPSS data

```{r}
rm(list =ls())
social_survey <- read_sav("./GSS7218_R3.sav") 
```
```{r}
social_survey <- janitor::clean_names(social_survey) 
social_survey <- janitor:: remove_empty(social_survey,which =c("rows","cols"))
```
```{r}
# A <- head(social_survey,1)
# write.csv(A,file="socialsurvey.csv",row.names = F)

# write_xlsx(list(GSS=social_survey))
```
```{r}
# social_survey <- read_csv("./socialsurvey.csv")
```

```{r}
social_survey %>% select(year,agewed) %>% group_by(year) %>%
  summarise(avg_age = mean(agewed,na.rm=T) ) %>%
  ggplot(aes(x=year,y=avg_age)) + geom_line() +
  labs(title = "Average Age Wed")

```
```{r}
social_survey %>% filter(educ >=13) %>% select(year,educ) %>% count(year,educ) %>%
  ggplot(aes(x=year,y=n)) + geom_line(aes(col= factor(educ),group = educ)) + labs(title = "Number of College attended \n by Year and Grade Completed")

```

### Number of People completing 12 grade


```{r}
social_survey %>% filter(educ ==12) %>% select(year,educ) %>% count(year,educ) %>%
  ggplot(aes(x=year,y=n)) + geom_line(aes(col= factor(educ),group = educ)) + labs(title = "Number of Respondants Who Completed High School by Year") +
  geom_smooth(aes(x=year,y=n))
```

## Count of respondents by Year

```{r}
social_survey %>% count(year) %>%
  ggplot(aes(x=year,y=n)) + geom_line() +
  labs(title = "Number of Respondents by Year",
       x="Year",y="Number of Respondents")
```

### Race,Income,Sex,Age and PartyId

```{r}
social_survey$race <- as.factor(social_survey$race)
df <- social_survey %>%select(year,income,race,sex,age,partyid) 

```
```{r}
 df$race <- recode(df$race,`1` = "White", `2` = "Other",`3` = "Other"
    )

```
```{r}
df %>% group_by(year,race) %>% 
  summarise(Count = n()) %>%
  ggplot() + geom_line(aes(x=year,y=Count)) +
  facet_wrap(~race) +
  labs(title = "Number of Respondents by Race (White,Not White)")
```

### By Sex

```{r}
df %>% group_by(year,sex) %>% 
  summarise(Count = n()) %>%
  ggplot() + geom_line(aes(x=year,y=Count)) +
  facet_wrap(~sex) +
  labs(title = "Number of Respondents by Sex")
```

### By Age

```{r}
df %>% group_by(year,age) %>% 
  summarise(Count = n()) %>%
  ggplot() + geom_line(aes(x=year,y=Count)) +
  facet_wrap(~age) +
  labs(title = "Number of Respondents by Age")
```

```{r}
df %>% group_by(year,partyid) %>% 
  summarise(Count = n()) %>%
  ggplot() + geom_line(aes(x=year,y=Count)) +
  facet_wrap(~partyid) +
  labs(title = "Number of Replies by Political Party")
```